### ISSUE TITLE
Wrong init code in AppContainer (fix included)

### ISSUE THREAD

**Issue by jakubjosef** [Blackfry/cra-flask#1]
Hello,
I just tried to run your project because that fork you starting with is quite obsolete nowadays.
But i found one big blocking issue and I wanna help others. 
I found wrong init code in componentWillMount method inside the AppContainer react component.
```
  componentWillMount() {
    let result = (checkAuth()
    .then(response => {
      return response.status === 200
        })
    )
    
    if (result) {
      this.props.loginUserSuccess(localStorage.getItem('token'));
      this.setState({ loaded: true });
    }
```
This code is total nonsense, you can't use return inside the promise callback.
In this case result will be always executed as true in that if and page load will fails with:

InvalidTokenError: Invalid token specified: Cannot read property 'replace' of undefined

This is my hotfix solution:
```
    let that = this;
    let result = (checkAuth()
      .then(response => {
        console.log(response);
        if (response.status === 200) {
            that.props.loginUserSuccess(localStorage.getItem('token'));
            that.setState({ loaded: true });
        }
      })
    );
```

**Comment by mark-dickie** [comment]
I should turn on notifications for this repo I guess, anyway fixed thanks
